### ISSUE TITLE
Openshift Installs Fails on ImageStream Create

### ISSUE THREAD

**Issue by dmc5179** [jbossdemocentral/rhpam7-mortgage-demo#6]
When using the Openshift installation method no pods are deployed because no images are pulled. Red Hat has been migrating everything to registry.redhat.io which requires a username/password or a service account. To use the service account you have to download the secret from the registry and import it into OpenShift. I'm pretty new to OpenShift but after spending several hours trying to figure out how to edit the scripts in this repo or the image stream yaml file I gave up. I pulled the images from the redhat repo and uploaded them to my own quay account, edited the image stream yaml to point to those images, and it all worked fine.

I'm sure that the maintainers of this repo could say that configuring Openshift with the right secrets to pull the images from the redhat repo is outside the scope of this tutorial but without that part it is impossible to get this demo to work.

**Comment by DuncanDoyle** [comment]
Yeah, I noticed this myself last week, and quickly fixed the rhpam7-install-demo and rhdm7-install-demo. I will fix this one today.

It will require users of the demo to have a Red Hat Network account, which can be the account you have on "https://developers.redhat.com".

**Comment by DuncanDoyle** [comment]
Fixed: https://github.com/jbossdemocentral/rhpam7-mortgage-demo/commit/fff6d5ad16ece4a85817a99bd355fdb96e475977

Note that the install scripts now require you to login with an RHN account, for example your https://developers.redhat.com account
